apiVersion: batch/v1
kind: Job
metadata:
  name: alembic-upgrade
spec:
  template:
    spec:
      containers:
      - name: alembic
        image: migrations
        imagePullPolicy: IfNotPresent
        env:
          - name: POSTGRES_CONNECTION_STRING
            value: "postgresql://pguser:pgpass@psql-db-service:5432/db"
      restartPolicy: Never
  backoffLimit: 3

