
apiVersion: batch/v1
kind: Job
metadata:
  name: alembic-upgrade-mock
spec:
  template:
    spec:
      containers:
      - name: alembic
        image: alembic
        imagePullPolicy: IfNotPresent
        env:
          - name: POSTGRES_CONNECTION_STRING
            value: "postgresql://pguser:pgpass@mock-db-service:5432/mock_db"
      restartPolicy: Never
  backoffLimit: 3

