version: "3.9"

services:
  database:
    container_name: mock_db
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: pgpass
      POSTGRES_USER: pguser
      POSTGRES_DB: mock_db
    ports:
      - "5433:5432"
    volumes:
      - ./resources/volumes/local/pgdata:/var/lib/postgresql/data
    restart: always
    network_mode: "bridge"